name: CI and CD pipeline
on:
  workflow_dispatch:
jobs:
  inputs:
     uses: chaithragudimalla/testingOnPrem/.github/workflows/main.yml@feature
     with:
       token: ${{ secrets.TOKEN }}
  check:
     needs: inputs
     if: "contains(needs.inputs.outputs.buildTool, 'maven')"
     uses: GithubActions-Group-Project/Project/.github/workflows/maven.yaml@main    
     with:
        dockerImage: ubuntu
        token: ${{ secrets.GITHUB_TOKEN }}
        
  check1:
    needs: inputs
    if: "contains(needs.inputs.outputs.buildTool, 'npm') && contains(needs.inputs.outputs.language, 'java') && contains(needs.inputs.outputs.javaVersion, 1.8)"
    uses: GithubActions-Group-Project/Project/.github/workflows/npm.yaml@main
    with:
      image_name: ubuntu
    secrets:
       registry_username: ${{ secrets.REGISTRY_USERNAME }}
       registry_password: ${{ secrets.REGISTRY_PASSWORD }}
       token: ${{ secrets.GITHUB_TOKEN }}
  check2:
    needs: inputs
    if: "contains(needs.inputs.outputs.buildTool, 'ng') && contains(needs.inputs.outputs.language, 'java') && contains(needs.inputs.outputs.javaVersion, 1.8)"
    uses: GithubActions-Group-Project/Project/.github/workflows/npm2.yaml@main
    with:
      image_name: ubuntu
    secrets:
       registry_username: ${{ secrets.REGISTRY_USERNAME }}
       registry_password: ${{ secrets.REGISTRY_PASSWORD }}
       token: ${{ secrets.GITHUB_TOKEN }}
       
  check3:
    needs: inputs
    if: "contains(needs.inputs.outputs.buildTool, 'ng')"
    uses: GithubActions-Group-Project/Project/.github/workflows/ng.yaml@main
    with:
        dockerImage: ubuntu
        token: ${{ secrets.GITHUB_TOKEN }}
        
  Code-Quality:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [check, check1, check2]
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - uses: actions/download-artifact@v3
         with:
           name: artifact1
       - name: code Analysis
         run: echo 'mvn sonar:sonar'
          
  security-scan:
    if: ${{ always() }}
    needs: [Code-Quality]
    #if: github.event.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - name: scanning
         run: echo 'scanning'
         
  Quality-Gates:
    if: ${{ always() }}
    #if: github.event.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    needs: [security-scan]
    steps:
       - uses: actions/checkout@v3
       - name: CodeAnalysis_Quality_gates
         run: echo 'code analysis quality gates'
       - name: SecurityAnalysis_Quality_gates
         run: echo 'security analysis quality gates'
         
  ChangeRequest_Validation:
    if: ${{ always() && github.event.ref == 'refs/heads/main' }}
    needs: [Quality-Gates]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: validations status
        run: echo 'ChangeRequest Validation "performed"'
    
  Deploy_Develop:
    if: ${{ always() && github.event.ref == 'refs/heads/feature' }}
    needs: [Quality-Gates]
    runs-on: ubuntu-latest
    steps:
       - name: testing
         run: echo "success"
         
  Deploy_Stage:
    if: ${{ always() && github.event.ref == 'refs/heads/develop' }}
    needs: [Quality-Gates]
    runs-on: ubuntu-latest
    environment: 
      name: Staging 
    steps:
       - uses: actions/checkout@v3
       - name: deploying into develop branch
         run: echo 'develop branch'
         
  Deploy_PROD:
    if: ${{ always() && github.event.ref == 'refs/heads/main' }}
    needs: [ChangeRequest_Validation]
    runs-on: ubuntu-latest
    environment: 
      name: Production
    steps:
       - uses: actions/checkout@v3
       - name: deploying to Prod
         run: echo 'master branch'
